spring:
    application:
        name: six-degrees-app
    security:
        user:
            name: admin
            password: admin
    docker:
        compose:
            lifecycle-management: start_and_stop
            file: compose-dev.yaml
    threads:
        virtual:
            enabled: true
    neo4j:
        uri: ${NEO4J_URI}
        authentication:
            username: ${NEO4J_USERNAME}
            password: ${NEO4J_PASSWORD}
logging:
    level:
        org.kidoni: debug
        org.springframework.data.neo4j.cypher.unrecognized: error
tmdb:
    api:
        url: "https://api.themoviedb.org/"
        access-token: ${TMDB_ACCESS_TOKEN}
management:
    endpoints:
        web:
            exposure:
                include: '*'
