spring:
    application:
        name: six-degrees-app
    security:
        user:
            name: admin
            password: admin
    docker:
        compose:
            lifecycle-management: start_only
            file: compose-dev.yaml
    threads:
        virtual:
            enabled: true
    data:
        neo4j:
            # database: tmdb-database  # Using default 'neo4j' database (Community Edition only supports one DB)
neo4j:
    uri: ${NEO4J_URI}
    authentication:
        username: ${NEO4J_USERNAME}
        password: ${NEO4J_PASSWORD}
logging:
    level:
        org.kidoni: debug
tmdb:
    api:
        url: "https://api.themoviedb.org/"
        api-key: ${TMDB_API_TOKEN}
        access-token: ${TMDB_ACCESS_TOKEN}
